# Generated by Django 2.2.2 on 2020-01-01 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20191231_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitchuser',
            name='session_key',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
