# Generated by Django 3.1.2 on 2020-10-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_pitchuser_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
