# Generated by Django 3.1.2 on 2020-12-05 03:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('height', models.IntegerField(default=128)),
                ('width', models.IntegerField(default=128)),
                ('desc_info', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcrPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField(default=0.0)),
                ('frame_num', models.IntegerField(default=0)),
                ('current_frame', models.IntegerField(default=0)),
                ('is_vertical', models.BooleanField(default=False)),
                ('assist_num', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('title', 'create_user_id')},
            },
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('frame_id', models.IntegerField(default=-1)),
                ('data_byte', models.CharField(default='', max_length=255, null=True)),
                ('data_type', models.CharField(max_length=255)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('ocrPDF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrpdf')),
            ],
            options={
                'unique_together': {('ocrPDF', 'frame_id')},
            },
        ),
        migrations.CreateModel(
            name='OcrLabelingPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('polygon', models.BinaryField(null=True)),
                ('edit_count', models.IntegerField(default=0)),
                ('labeling_count', models.IntegerField(default=0)),
                ('labeling_content', models.BooleanField(default=False)),
                ('pdfImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.pdfimage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcrAssistRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('owner', 'create_user_id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='PolygonElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('desc_info', models.TextField(default='', null=True)),
                ('elem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.chineseelem')),
                ('polygon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrlabelingpolygon')),
            ],
            options={
                'unique_together': {('polygon', 'elem', 'create_user_id')},
            },
        ),
        migrations.CreateModel(
            name='OcrAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_frame', models.IntegerField(default=0)),
                ('assist_user_name', models.CharField(max_length=255, null=True)),
                ('is_vertical', models.BooleanField(default=False)),
                ('ocrPDF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrpdf')),
            ],
            options={
                'unique_together': {('ocrPDF', 'assist_user_name')},
            },
        ),
        migrations.CreateModel(
            name='ImageUserConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('rotate_degree', models.FloatField(default=0)),
                ('is_vertical', models.BooleanField(default=False)),
                ('filter_size', models.IntegerField(default=16)),
                ('entropy_thr', models.FloatField(default=0.9)),
                ('projection_thr_strict', models.FloatField(default=0.6)),
                ('projection_thr_easing', models.FloatField(default=0.1)),
                ('center_x', models.FloatField(default=0)),
                ('center_y', models.FloatField(default=0)),
                ('zoom_scale', models.FloatField(default=1)),
                ('polygon_id_thr', models.IntegerField(default=-1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.pdfimage')),
            ],
            options={
                'unique_together': {('image', 'create_user_id')},
            },
        ),
        migrations.CreateModel(
            name='CharacterElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('character', models.CharField(max_length=16, null=True)),
                ('elem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.chineseelem')),
            ],
            options={
                'unique_together': {('character', 'elem', 'create_user_id')},
            },
        ),
    ]
