# Generated by Django 2.2.2 on 2020-01-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.FloatField(default=0.0)),
                ('frame_num', models.IntegerField(default=0)),
                ('current_frame', models.IntegerField(default=0)),
                ('is_vertical', models.BooleanField(default=False)),
                ('assist_num', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('title', 'create_user_id')},
            },
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('frame_id', models.IntegerField(default=-1)),
                ('data_byte', models.BinaryField(null=True)),
                ('data_type', models.CharField(max_length=255)),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('ocrPDF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.OcrPDF')),
            ],
            options={
                'unique_together': {('ocrPDF', 'frame_id')},
            },
        ),
        migrations.CreateModel(
            name='OcrLabelingPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('polygon', models.BinaryField(null=True)),
                ('is_fine', models.BooleanField(default=False)),
                ('pdfImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.PDFImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OcrAssistRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'unique_together': {('owner', 'create_user_id', 'title')},
            },
        ),
        migrations.CreateModel(
            name='OcrAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('current_frame', models.IntegerField(default=0)),
                ('assist_user_name', models.CharField(max_length=255, null=True)),
                ('is_vertical', models.BooleanField(default=False)),
                ('ocrPDF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.OcrPDF')),
            ],
            options={
                'unique_together': {('ocrPDF', 'assist_user_name')},
            },
        ),
        migrations.CreateModel(
            name='ImageUserConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('rotate_degree', models.FloatField(default=0)),
                ('is_vertical', models.BooleanField(default=False)),
                ('entropy_thr', models.FloatField(default=0.9)),
                ('projection_thr_strict', models.FloatField(default=0.6)),
                ('projection_thr_easing', models.FloatField(default=0.1)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.PDFImage')),
            ],
            options={
                'unique_together': {('image', 'create_user_id')},
            },
        ),
    ]
