# Generated by Django 2.2.2 on 2020-01-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrlabelingpolygon',
            name='is_fine',
        ),
        migrations.AddField(
            model_name='ocrlabelingpolygon',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrlabelingpolygon',
            name='labeling_content',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='ocrlabelingpolygon',
            name='labeling_count',
            field=models.IntegerField(default=0),
        ),
    ]
