# Generated by Django 2.2.2 on 2020-06-26 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_ocrlabelingpolygon_labeling_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterelem',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='chineseelem',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='imageuserconf',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ocrassist',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ocrassistrequest',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ocrlabelingpolygon',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ocrpdf',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='pdfimage',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='polygonelem',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 13, 54, 22, 653247), help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
