# Generated by Django 2.2.2 on 2020-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_auto_20200108_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuserconf',
            name='filter_size',
            field=models.IntegerField(default=16),
        ),
    ]
