# Generated by Django 3.1.2 on 2020-12-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_chineseelem_elem_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chineseelem',
            name='elem_group',
        ),
    ]
