# Generated by Django 2.2.2 on 2020-04-15 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20200415_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageuserconf',
            old_name='room_scale',
            new_name='zoom_scale',
        ),
    ]
