# Generated by Django 2.2.2 on 2020-07-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20200626_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfimage',
            name='data_byte',
        ),
    ]
