# Generated by Django 2.2.2 on 2020-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_remove_pdfimage_data_byte'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfimage',
            name='data_byte',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
