# Generated by Django 2.2.2 on 2020-04-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_auto_20200415_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChineseElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('image_bytes', models.BinaryField()),
                ('desc', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CharacterElem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('character', models.CharField(max_length=16, null=True)),
                ('elem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ChineseElem')),
            ],
            options={
                'unique_together': {('character', 'elem', 'create_user_id')},
            },
        ),
    ]
