# Generated by Django 3.1.2 on 2020-12-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_chineseelem_elemgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chineseelem',
            name='elemgroup',
        ),
    ]
