# Generated by Django 2.2.2 on 2020-07-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0006_pdfimage_data_byte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageuserconf',
            name='center_y',
            field=models.FloatField(default=0),
        ),
    ]
