# Generated by Django 2.2.2 on 2020-04-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_characterelem_chineseelem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chineseelem',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
