# Generated by Django 2.2.2 on 2020-07-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0007_auto_20200703_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrpdf',
            name='is_vertical',
        ),
    ]
