# Generated by Django 2.2.2 on 2020-07-06 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0008_remove_ocrpdf_is_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrassist',
            name='is_vertical',
        ),
    ]
