# Generated by Django 2.2.2 on 2020-07-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_remove_ocrassist_is_vertical'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrassist',
            name='direction',
            field=models.CharField(default='horizontal', max_length=255),
        ),
        migrations.AddField(
            model_name='ocrpdf',
            name='direction',
            field=models.CharField(default='horizontal', max_length=255),
        ),
    ]
