# Generated by Django 3.1.2 on 2020-12-22 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0009_modeldoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chineseelem',
            name='ocrmodel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrmodel'),
        ),
    ]
