# Generated by Django 3.1.2 on 2020-12-28 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0010_chineseelem_ocrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间')),
                ('create_user_id', models.CharField(help_text='创建人id', max_length=255, verbose_name='创建人id')),
                ('is_deleted', models.BooleanField(default=False)),
                ('docs', models.TextField(blank=True)),
                ('name', models.CharField(max_length=255)),
                ('trainmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocr.ocrmodel')),
            ],
            options={
                'unique_together': {('trainmodel', 'name', 'create_user_id')},
            },
        ),
    ]
