# Generated by Django 2.2.2 on 2020-07-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0010_auto_20200706_0645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrassist',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='ocrpdf',
            name='direction',
        ),
        migrations.AddField(
            model_name='ocrassist',
            name='is_vertical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ocrpdf',
            name='is_vertical',
            field=models.BooleanField(default=False),
        ),
    ]
