# Generated by Django 2.2.2 on 2020-04-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0010_polygonelem'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterelem',
            name='height',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='characterelem',
            name='width',
            field=models.IntegerField(default=128),
        ),
    ]
