# Generated by Django 3.1.2 on 2020-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0011_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
