# Generated by Django 3.1.2 on 2020-12-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_training_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='device',
            field=models.CharField(default='gpu', max_length=32),
        ),
        migrations.AddField(
            model_name='training',
            name='fittype',
            field=models.CharField(default='contain', max_length=32),
        ),
        migrations.AddField(
            model_name='training',
            name='imageheight',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='training',
            name='imagewidth',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='training',
            name='isresized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='isrotated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='issplit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='splitheight',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='training',
            name='splitoverlap',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='training',
            name='splitwidth',
            field=models.IntegerField(default=640),
        ),
        migrations.AddField(
            model_name='training',
            name='trainbatch',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='training',
            name='trainepoch',
            field=models.IntegerField(default=4000),
        ),
        migrations.AddField(
            model_name='training',
            name='trainscale',
            field=models.CharField(default='yolov5m', max_length=32),
        ),
        migrations.AddField(
            model_name='training',
            name='trainsize',
            field=models.IntegerField(default=640),
        ),
    ]
