# Generated by Django 2.2.2 on 2020-05-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0012_auto_20200423_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonelem',
            name='desc_info',
            field=models.TextField(default='', null=True),
        ),
    ]
